default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: user1
  password: 1234
  pool: 5

development:
  <<: *default
  database: post_management_development

test:
  <<: *default
  database: post_management_test

production:
  <<: *default
  database: post_management_production
  username: arif
  password: <%= ENV['POSTGRES_PASSWORD'] %>

